// ============================================================
// firebase_options.dart
//
// This file is generated by the FlutterFire CLI tool.
// To generate YOUR version, run:
//
//   dart pub global activate flutterfire_cli
//   flutterfire configure
//
// Replace ALL values below with the ones from your own
// Firebase project console.
// ============================================================

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ── Replace these with your actual Firebase config values ──────────────────

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:257559916988:android:1f4c53ecdaf9088a9cfbb9',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'diary-app-f4689',
    authDomain: 'diary-app-f4689.firebaseapp.com',
    storageBucket: 'diary-app-f4689.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY',
    appId: '1:257559916988:android:1f4c53ecdaf9088a9cfbb9',
    messagingSenderId: '257559916988',
    projectId: 'diary-app-f4689',
    storageBucket: 'diary-app-f4689.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'diary-app-f4689',
    storageBucket: 'diary-app-f4689.appspot.com',
    iosClientId: 'YOUR_IOS_CLIENT_ID',
    iosBundleId: 'com.example.diaryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosClientId: 'YOUR_MACOS_CLIENT_ID',
    iosBundleId: 'com.example.diaryApp',
  );
}