// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6GStVbJYYbFT7Y1cJ6wDHaECn-6asyWA',
    appId: '1:257559916988:web:1412e3a65e7c6b7f9cfbb9',
    messagingSenderId: '257559916988',
    projectId: 'diary-app-f4689',
    authDomain: 'diary-app-f4689.firebaseapp.com',
    storageBucket: 'diary-app-f4689.firebasestorage.app',
    measurementId: 'G-LY3R8DVKXK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo6lGDAV3hujVgDNqGbiVPPQ61J0jgrJk',
    appId: '1:257559916988:android:735649222d4da8049cfbb9',
    messagingSenderId: '257559916988',
    projectId: 'diary-app-f4689',
    storageBucket: 'diary-app-f4689.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmZhfKNqz4BlJUHwLHRqa3sro_VcvqYas',
    appId: '1:257559916988:ios:3366da7ef4de03869cfbb9',
    messagingSenderId: '257559916988',
    projectId: 'diary-app-f4689',
    storageBucket: 'diary-app-f4689.firebasestorage.app',
    iosClientId: '257559916988-p57fomb7ui9rbdckspa5cs86nh9ci82p.apps.googleusercontent.com',
    iosBundleId: 'com.example.diaryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmZhfKNqz4BlJUHwLHRqa3sro_VcvqYas',
    appId: '1:257559916988:ios:3366da7ef4de03869cfbb9',
    messagingSenderId: '257559916988',
    projectId: 'diary-app-f4689',
    storageBucket: 'diary-app-f4689.firebasestorage.app',
    iosClientId: '257559916988-p57fomb7ui9rbdckspa5cs86nh9ci82p.apps.googleusercontent.com',
    iosBundleId: 'com.example.diaryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6GStVbJYYbFT7Y1cJ6wDHaECn-6asyWA',
    appId: '1:257559916988:web:fc932bac24e9304c9cfbb9',
    messagingSenderId: '257559916988',
    projectId: 'diary-app-f4689',
    authDomain: 'diary-app-f4689.firebaseapp.com',
    storageBucket: 'diary-app-f4689.firebasestorage.app',
    measurementId: 'G-M1KBVM3ST7',
  );
}
